window.data = {
  cheese: 0,
  totalCPS: 0,
  producers: [
    {
      id: "mr._mouse",
      description: "Mr. Cheesy Mouse will steal some cheese for you.",
      price: 10,
      unlocked: false,
      cps: 1,
      qty: 0,
    },
    {
      id: "cheese_cow",
      description: "Where did you think cheese comes from?",
      price: 50,
      unlocked: false,
      cps: 2,
      qty: 0,
    },
    {
      id: "cheese_goat",
      description: "Don't knock it till you try it.",
      price: 100,
      unlocked: false,
      cps: 5,
      qty: 0,
    },
    {
      id: "fondue_pot",
      description:
        "Mmmmm... You can dip anything into your delicious pot of melted cheese.",
      price: 500,
      unlocked: false,
      cps: 10,
      qty: 0,
    },
    {
      id: "giant_cheese_wheel",
      description: "Bigger than yo momma's house!",
      price: 1000,
      unlocked: false,
      cps: 20,
      qty: 0,
    },
    {
      id: "cheese_farm",
      description: "cheese",
      price: 5000,
      unlocked: false,
      cps: 50,
      qty: 0,
    },
    {
      id: "cheese_&_wine_party",
      description: "Nice & cozy place for the cheese farmers to live in.",
      price: 10000,
      unlocked: false,
      cps: 75,
      qty: 0,
    },
    {
      id: "cheese_factory",
      description: "How else will you catch up to capitalism?",
      price: 50000,
      unlocked: false,
      cps: 100,
      qty: 0,
    },
    {
      id: "gourmet_cheese_shop",
      description: "Time to get these yuppies hooked on you delicious cheese.",
      price: 100000,
      unlocked: false,
      cps: 200,
      qty: 0,
    },
    {
      id: "cheese_castle",
      description:
        "If you don't live in a cheese castle, how else will everyone know you are the cheese king?!",
      price: 500000,
      unlocked: false,
      cps: 500,
      qty: 0,
    },
    {
      id: "cheese_kingdom",
      description: "Yes, you are the king. All these plebs work for you!",
      price: 1000000,
      unlocked: false,
      cps: 1000,
      qty: 0,
    },
    {
      id: "cheese_moon",
      description: "Wow, you colonized the moon!",
      price: 5000000,
      unlocked: false,
      cps: 2000,
      qty: 0,
    },
  ],
};
